# vi: ft=ruby

default_platform :ios

platform :ios do
  desc "Run unit tests."
  lane :run_tests do
    destination = "platform=iOS Simulator,name=iPhone 6,OS=9.2"
    scan(
      scheme: 'Wikipedia',
      destination: destination)
  end
end