# vi: ft=ruby

default_platform :ios

platform :ios do
  desc "Run all test schemes."
  lane :run_all_tests do
    run_tests(scheme: 'Wikipedia')
    run_tests(scheme: 'WikipediaRTL')
  end

  desc "Run unit tests."
  lane :run_tests do |options|
    destination = "platform=iOS Simulator,name=iPhone 6,OS=9.2"
    scan(
      scheme: options[:scheme],
      destination: destination)
  end
end